apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: localisation-services
  description: >-
    Manages the infrastructure for Platform translation and localisation
    services.
  labels:
    license: MIT
spec:
  type: website
  lifecycle: experimental
  owner: cds-snc
