version: '3'

services:
  dev:
    image: mcr.microsoft.com/vscode/devcontainers/base:buster@sha256:8b1ae3b7d73d9518849bd5a3d6dfbdbb8d5a57bf4b03ebacc251b1905dff01cb
    volumes:
        - ./:/workspace:cached
    command: sleep infinity    

  weblate:
    build:
      context: ./weblate/docker
    image: weblate:5.1
    restart: unless-stopped
    env_file:
      - .env.example
    ports:
      - 8080:8080
      - 4443:4443
    tmpfs:
      - /run
      - /tmp
    volumes:
      - weblate-cache:/app/cache
    depends_on:
      - database
      - cache

  database:
    image: postgres:15.4-alpine@sha256:35ce2187f2f7fb75e8e79493e13743596c21eb3789ff41ece145ae04d06e93a5
    restart: unless-stopped
    env_file:
      - .env.example
    volumes:
      - postgres-data:/var/lib/postgresql/data

  cache:
    image: redis:7-alpine@sha256:5482672695b73780afeddb2ee84d58f393f16f34718d76b246c76afe27465d4c
    restart: unless-stopped
    env_file:
      - .env.example
    command: [redis-server, --save, '60', '1']
    volumes:
      - redis-data:/data

volumes:
  weblate-cache: {}
  postgres-data: {}
  redis-data: {}
