skip-check:
  - CKV_AWS_103 # Load balancer false-positive; listerner is using TLS 1.3
  - CKV_AWS_136 # ECR service encryption key is acceptableS
  - CKV_AWS_158 # CloudWatch service encryption key is acceptable
  - CKV_AWS_184 # EFS secvice encryption key is acceptable
  - CKV_AWS_191 # Elasticache service encryption key is acceptable
  - CKV_AWS_192 # WAF no need to prevent Log4j vulnerabilities
  - CKV2_AWS_5  # VPC: security groups are attached in subsequent modules